select '2018-01-01' as DATE_DEBUT,
	'2018-12-31' as DATE_FIN,
	SMED_COD_DIN as DIN, -- ou SMED_CODE_DENOM_COMNE as DENOM
	sum(SMED_MNT_AUTOR_MED) as MNT_MED,
	sum(SMED_MNT_AUTOR_FRAIS_SERV) as MNT_SERV,
	sum(SMED_MNT_AUTOR_FRAIS_SERV + SMED_MNT_AUTOR_MED) as MNT_TOT,
	count(distinct SMED_NO_INDIV_BEN_BANLS) as COHORTE,
	count(*) as NBRE_RX,
	sum(SMED_QTE_MED) as QTE_MED,
	sum(SMED_NBR_JR_DUREE_TRAIT) as DUREE_TX
from PROD.V_DEM_PAIMT_MED_CM
where SMED_DAT_SERV between '2018-01-01' and '2018-12-31'
	and SMED_COD_DIN in (30848, 585092) -- ou SMED_CODE_DENOM_COMNE in ('47092','47135')
	and (SMED_COD_SERV_1 is null or SMED_COD_SERV_1 not in ('1', 'AD'))
group by DIN
order by DIN;