---
output:
  md_document:
    variant: markdown_github
  pdf_document:
    toc_depth: 2
    highlight: default
urlcolor: blue
---
  
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  echo = FALSE, results = "asis"
)
```

## Librairie [`inesss` `r paste0('v.',as.character(packageVersion('inesss')))`](https://github.com/INESSS-QC/inesss1)

### v0.7.1
* SQL_comorbidity() : `lubridate::years(lookup) - n1 modifié par %m-% months(lookup*12) - n2`  
%m-% ne renvoie pas d'erreur lorsque la date est le 29 février.  
Une date peut en confirmer une autre lorsque c'est dans l'intervalle [n1;n2]. Puisque n2 > n1, c'est cette valeur qui doit être utilisée.

### [v0.7.0](https://github.com/INESSS-QC/inesss1/pull/14)
* Nouveaux datas pour l'étude de la comorbidité : `Combine_Dx_CCI_INSPQ18`, `Charlson_Dx_CCI_INSPQ18`, `Elixhauser_Dx_CCI_INSPQ18`, `Charlson_Dx_UManitoba16` et `ComorbidityWeights`.
* Ajustements des arguments des fonctions en lien avec l'étude de la comorbidité : `comorbidity`, `SQL_comorbidity_diagn` et `SQL_comorbidity`.
* Lors du calcul des *scores* de comorbidité, tous les individus de la cohorte sont présents.

### [v0.6.3](https://github.com/INESSS-QC/inesss1/pull/13)
* Addins `Datas INESSS` qui permet d'explorer les datasets de la librairie.
* MaJ méthode *stat_gen1* : filtre par défaut `where SMED_NBR_JR_DUREE_TRAIT > 0`.
* MaJ fonction `SQL_comorbidity` qui avait un message d'erreur lors du tri des évènements obstétriques.

### [v0.6.2](https://github.com/INESSS-QC/inesss1/commit/d223ab8038d16db8b7c7949f7289f71b2fa30fb0)
* Data `I_APME_DEM_AUTOR_CRITR_ETEN_CM` section `DES_COURT_INDCN_RECNU`.

### [v0.6.1](https://github.com/INESSS-QC/inesss1/pull/12)
* Fonction `inesss_excel_macros`.

### [v0.6.0](https://github.com/INESSS-QC/inesss1/pull/11)
* Fonction `date_ymd`.
* Fonctions `query_naif_switch1` et `SQL_naif_switch1`
* Méthode `naif_switch1` dans le formulaire (via EXCEL seulement).
* Nouvelle structure des `datas` décrivant les bases de données de la RAMQ. `list` décrivant un ou plusieurs éléments.

### [v0.5.2](https://github.com/INESSS-QC/inesss1/commit/198d47ddaf7ff50fb956704e857923e3b6c7caf7)
* Documentation `Comorbidity_diagn_codes` : Description des codes de diagnostiques.
* Argument `keep_confirm_data` de la fonction `comorbidity` permet de mettre en attribut le data indiquant la date de repérage du diagnostic ainsi que sa date de confirmation.
* Argument `exclu_diagn` de la fonction `SQL_comorbidity_diagn` permet d'exclure un code de diganostic de l'analyse.
* Arguments `keep_confirm_data` et `exclu_diagn` ajouté à la fonction `SQL_comorbidity`, car utilise les fonctions `comorbidity` et `SQL_comorbidity_diagn`.

### [v0.5.1](https://github.com/INESSS-QC/inesss1/commit/7a4055b3937c17c67af24723f8aae2938dfed8a1)
* Data `I_APME_DEM_AUTOR_CRITR_ETEN_CM`.
* Documentation : Corrections mineures.

### [v0.5.0](https://github.com/INESSS-QC/inesss1/pull/10)
* Fonction `SQL_comorbidity`.
* Fonction `SQL_comorbidity_diagn`.
* Fonction `SQL_obstetric`.
* Fonction `comorbidity`.
* Data `Comorbidity_diagn_codes`.
* Data `Charlson_diagn_codes`.
* Data `Elixhauser_diagn_codes`.
* Data `Comorbidity_weights`.
* Data `Obstetrics_diagn_codes`.


#### [v0.4.0](https://github.com/INESSS-QC/inesss1/pull/7)
* `query_stat_gen1()` remplace `stat_gen1_query()`.
* `SQL_stat_gen1()` utilise l'argument *group_by* au lieu de *result_by*. `group_by='Codes'` au lieu de `'Périodes'`.
* Mise à jour du fichier *AIDE-FORMULAIRE-EXEMPLES-ARGUMENTS.xlsx*.
* Mise à jour du fichier *AIDE-FORMULAIRE-EXEMPLES-RÉSULTATS.xlsx*.
* Data `V_DEM_PAIMT_MED_CM.SMED_COD_DIN`.
* Data `V_DEM_PAIMT_MED_CM.SMED_COD_SERV`.
* Data `V_DENOM_COMNE_MED`.
* Data `V_DES_COD`.
* Data `V_PRODU_MED.NOM_MARQ_COMRC`.


### [v0.3.0](https://github.com/INESSS-QC/inesss1/pull/6)
* Le formulaire, section *Requêtes via Excel*, indique le répertoire du fichier sélectionné.
* Statistiques générales (`stat_gen1`) permet d'afficher les résultats par `Teneur` et `Format`.
* Mise à jour de la documentation : 2021-01-14.


### [v0.2.1](https://github.com/INESSS-QC/inesss1/pull/5)
* Nouvelle interface du formulaire, section *Statistiques générales* : 1) Diviser en trois section distinctes; 2) Le code SQL s'affiche en même temps que le tableau des résultats; 3) Bouton qui réinitialise les arguments.


### [v0.2.0](https://github.com/INESSS-QC/inesss1/pull/4)
* Fonction `formulaire()`.
* Fonction `sql_connexion()`.
* Fonction `sql_stat_gen1()`.
* Création du fichier *AIDE-FORMULAIRE_2021-01-06.pdf*.
* Création du fichier *LISEZ-MOI_2021-01-06.pdf*.
* Création du fichier *R_RTOOLS_INSTALLATION_2021-01-06.pdf*.
* Exemples au format Excel. Voir fichiers *AIDE-FORMULAIRE-EXEMPLES-ARGUMENTS.xlsx* et *AIDE-FORMULAIRES-EXEMPLES-RÉSULTATS.xlsx*.
* Démarrage du formulaire via les *Addins* de *RStudio*.


### v0.1.1.9000
* Documentation des datas *Pop_QC*, *RLS_convert* et *RLS_list*.
