---
title: "SQL_diagn"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SQL_diagn}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE,
  eval = FALSE
)
```

```{r setup, echo=FALSE, eval=TRUE}
library(inesss)
```

# Valeurs par défauts
```{r, eval=FALSE}
SQL_diagn(
  conn = SQL_connexion(),
  cohort = NULL,
  debut,
  fin,
  Dx_table,
  CIM = c('CIM9', 'CIM10'),
  dt_source = c('V_DIAGN_SEJ_HOSP_CM',
                'V_SEJ_SERV_HOSP_CM',
                'V_EPISO_SOIN_DURG_CM',
                'I_SMOD_SERV_MD_CM'),
  dt_desc = list(V_DIAGN_SEJ_HOSP_CM = 'MEDECHO',
                 V_SEJ_SERV_HOSP_CM = 'MEDECHO',
                 V_EPISO_SOIN_DURG_CM = 'BDCU',
                 I_SMOD_SERV_MD_CM = 'SMOD'),
  date_dx_var = 'admis',
  typ_diagn = c('A', 'P', 'S', 'D'),
  exclu_diagn = NULL,
  verbose = TRUE
)
```


# Requêtes SQL
Supposons les arguments suivants (sinon par défaut) :
```{r, eval=FALSE}
debut = '2018-01-01'
fin = '2020-12-31'
Dx_table = list(Infarctus = list(CIM9 = c("410%", "411%", "412%", "413%", "414%"),
                                 CIM10 = c("I21%", "I22%", "I23%", "I24%", "I25%")))
```

### I_SMOD_SERV_MD_CM
```{r, eval=FALSE, echo=FALSE}
cat(query_I_SMOD_SERV_MD_CM(debut, fin, unlist(Dx_table$Infarctus)),
    sep = "")
```
```{sql, eval=FALSE}
select SMOD_NO_INDIV_BEN_BANLS as ID,
       SMOD_DAT_SERV as DATE_DX
from PROD.I_SMOD_SERV_MD_CM
where SMOD_DAT_SERV between '2018-01-01' and '2020-12-31'
    and SMOD_COD_DIAGN_PRIMR like any ('410%', '411%', '412%', '413%', '414%', 'I21%', 'I22%', 'I23%', 'I24%', 'I25%')
    and SMOD_COD_STA_DECIS = 'PAY';
```

### V_DIAGN_SEJ_HOSP_CM
```{r, eval=FALSE, echo=FALSE}
cat(query_V_DIAGN_SEJ_HOSP_CM(debut, fin, Dx_table$Infarctus),
    sep = "")
```
```{sql, eval=FALSE}
select SHOP_NO_INDIV_BEN_BANLS as ID,
       SHOP_DAT_ADMIS_SEJ_HOSP as DATE_DX
from RES_SSS.V_DIAGN_SEJ_HOSP_CM
where SHOP_DAT_ADMIS_SEJ_HOSP between '2018-01-01' and '2020-12-31'
    and ((SHOP_COD_DIAGN_MDCAL_CLINQ like any ('I21%', 'I22%', 'I23%', 'I24%', 'I25%') and SHOP_NO_SEQ_SYS_CLA = 1)
         or
         (SHOP_COD_DIAGN_MDCAL_CLINQ like any ('410%', '411%', '412%', '413%', '414%') and SHOP_NO_SEQ_SYS_CLA = 4))
    and SHOP_TYP_DIAGN_SEJ_HOSP in ('A', 'P', 'S', 'D');
```

### V_EPISO_SOIN_DURG_CM
```{r, eval=FALSE, echo=FALSE}
cat(query_V_EPISO_SOIN_DURG_CM(debut, fin, unlist(Dx_table$Infarctus), "admis"),
    sep = "")
```
```{sql, eval=FALSE}
select SURG_NO_INDIV_BEN_BANLS as ID,
       SURG_DHD_EPISO_SOIN_DURG as DATE_DX
from RES_SSS.V_EPISO_SOIN_DURG_CM
where SURG_DHD_EPISO_SOIN_DURG between to_date('2018-01-01') and to_date('2020-12-31')
    and SURG_COD_DIAGN_MDCAL_CLINQ like any ('410%', '411%', '412%', '413%', '414%', 'I21%', 'I22%', 'I23%', 'I24%', 'I25%');
```

### V_SEJ_SERV_HOSP_CM
```{r, eval=FALSE, echo=FALSE}
cat(query_V_SEJ_SERV_HOSP_CM(debut, fin, unlist(Dx_table$Infarctus), "admis"),
    sep = "")
```
```{sql, eval=FALSE}
select SHOP_NO_INDIV_BEN_BANLS as ID,
       SHOP_DAT_ADMIS_SEJ_HOSP as DATE_DX
from RES_SSS.V_SEJ_SERV_HOSP_CM
where SHOP_DAT_ADMIS_SEJ_HOSP between '2018-01-01' and '2020-12-31'
    and SHOP_COD_DIAGN_MDCAL_CLINQ like any ('410%', '411%', '412%', '413%', '414%', 'I21%', 'I22%', 'I23%', 'I24%', 'I25%');
```

# Autres exemples

### V_DIAGN_SEJ_HOSP_CM
```{r}
# CIM10 seulement
Dx_table = list(Infarctus = list(CIM10 = c("I21%", "I22%", "I23%", "I24%", "I25%")))
# Date du diagnostic = Date de départ
date_dx_var = "depar"
# Aucun critère sur les types de diagnostics
typ_diagn = NULL
```
```{r, eval=FALSE, echo=FALSE}
cat(query_V_DIAGN_SEJ_HOSP_CM(debut, fin, Dx_table$Infarctus, date_dx_var, typ_diagn),
    sep = "")
```
```{sql, eval=FALSE}
select SHOP_NO_INDIV_BEN_BANLS as ID,
       SHOP_DAT_DEPAR_SEJ_HOSP as DATE_DX
from RES_SSS.V_DIAGN_SEJ_HOSP_CM
where SHOP_DAT_DEPAR_SEJ_HOSP between '2018-01-01' and '2020-12-31'
    and SHOP_COD_DIAGN_MDCAL_CLINQ like any ('I21%', 'I22%', 'I23%', 'I24%', 'I25%') and SHOP_NO_SEQ_SYS_CLA = 1
;
```


